# Generated by Django 4.2.2 on 2023-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0002_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=49),
        ),
    ]
