# Generated by Django 4.2.2 on 2023-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
