# Generated by Django 4.2.2 on 2023-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parent_account",
            field=models.BooleanField(default=True),
        ),
    ]
