# Generated by Django 4.2.2 on 2023-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0005_user_parent_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
