# Generated by Django 4.2.2 on 2023-07-14 07:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0006_task_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="parent_account",
        ),
    ]
