# Generated by Django 4.2.2 on 2023-07-14 16:57

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0009_child"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Child",
        ),
        migrations.CreateModel(
            name="Child",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kidsavings.user",),
            managers=[
                ("child", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
