# Generated by Django 4.2.2 on 2023-07-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0012_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="childUser",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childUser",
                to="kidsavings.child",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(default="jacko", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
