# Generated by Django 4.2.2 on 2023-07-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kidsavings", "0013_task_childuser_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="kidsavings.child",
            ),
        ),
    ]
